### ISSUE TITLE
unrecognized option `-a'

### ISSUE THREAD

**Issue by SantiMunin** [pascalh/BnfcCabal#1]
Hello,

first of all I want to thank you for your work.

I am trying to use bnfc-cabal so I execute it and get an error I don't understand:

```
$ bnfcCabal Language.cf
Type a version number, e.g. [0,1] for version 0.1
[0,1]
unrecognized option `-a'

usage: bnfc [--version] [--help] <target language> [<args>] file.cf
bnfcCabal: A bnfc error occured.
```

Could you help me here? Thanks a lot.

**Comment by pascalh** [comment]
Hi,

it looks like something in bnfc changed, which causes this problem. I will try to solve this issue tomorrow

**Comment by SantiMunin** [comment]
Amazing, thanks!

**Comment by pascalh** [comment]
Problem solved. Internally I was using an old syntax to call bnfc. CabalBnfc now (only) works with the newer releases of bnfc.

Please feel free to ask for features or other adjustments.
