### ISSUE TITLE
build-depends is not written in the .cabal generated file

### ISSUE THREAD

**Issue by SantiMunin** [pascalh/BnfcCabal#3]
Hello,

I re-run the program with the newest changes. What I get is close to compile but some fields needs to be added (basically build-depends with base and array dependencies). Looking at the source code it should work, so I open this issue because I don't know how to fix it.

Generated file:

```
name: language-XXX
version: 0.1
cabal-version: -any
build-type: Simple
license: UnspecifiedLicense
extra-source-files:
    Language/XXX/ParXXX.y
    Language/XXX/LexXXX.x
exposed-modules:
    Language.XXX.ErrM
    Language.XXX.AbsXXX
    Language.XXX.ParXXX
    Language.XXX.PrintXXX
    Language.XXX.LexXXX
exposed: True
buildable: True
hs-source-dirs: .
```

Lines 123-127 has the required fields but they are not written then. 

Thanks!

**Comment by pascalh** [comment]
It seems like the function [writePackageDescription](http://hackage.haskell.org/package/Cabal-1.22.0.0/docs/Distribution-PackageDescription-Parse.html#v:writePackageDescription) in cabal is broken or changed its behaviour in a newer version of cabal.

I tried to manually create a package description in ghci (loading the file `Bnfc-cabal.hs`) as follows

`let config = Config [0,1] "bnfc"`
`let pd = updatePd config "Haskell" emptyPackageDescription`

Evaluating `pd` in ghci prints the correct package description (also containing the dependencies).
When using the function [writePackageDescription](http://hackage.haskell.org/package/Cabal-1.22.0.0/docs/Distribution-PackageDescription-Parse.html#v:writePackageDescription) to write that very package description to a file, the dependencies are missing in the generated file:
`writePackageDescription "/tmp/fooooo.cabal" pd`

The function `writePackageDescription` internally uses [showPackageDescription](http://hackage.haskell.org/package/Cabal-1.22.0.0/docs/src/Distribution-PackageDescription-Parse.html#showPackageDescription), which causes the package dependecies to disappear.

I will ask the cabal developers whether this is a bug or they changed it on purpose.

**Comment by pascalh** [comment]
With an older version of cabal everything works fine. Just checkout [this state of cabalBnfc](https://github.com/pascalh/BnfcCabal/tree/2c1e5222a0ee6d5ca64fabd981d5b4c90f0f287e)) and set cabal dependencies to `Cabal >= 1.8 && < 1.22.0`.

**Comment by pascalh** [comment]
The global build depends attribute is depricated, hence I assigned the dependencies to the library.
